### PR TITLE
Fix node versión not supported #124

### LINKED ISSUE #124: Parameter ''using: node18' is not supported
Hi!

I started getting an error when commenting issues:

> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node18' is not supported, use 'docker', 'node12', 'node16' or 'node20' instead.')

You can see it here https://github.com/soker90/libros/actions/runs/6565329654

I resolved this by downgrading the action to v1.1.0

Thank you!

### PR DESCRIPTION
**Pull request by soker90**
Upgrade node version to v20 (It will be LST from 24 October)

Fix #124

### CODE REVIEW

**Comment by Zaid-maker** [comment]
I already made a fix

**Comment by Zaid-maker** [comment]
> Upgrade node version to v20 (It will be LST from 24 October)

**Comment by Zaid-maker** [comment]
I made a mistake in previous pr as I don't know action don't support node18 and Anand merge it but I fix it use node16 on action and fix the build issue

**Comment by AnandChowdhary** [comment]
Thanks @soker90  and @Zaid-maker!

**Comment by AnandChowdhary** [comment]
This should be fixed in 70fca5e. Thanks for your contribution!

**Pull request closed without merging**
