### PR TITLE
Fix build and permission issue

### PR DESCRIPTION
**Pull request by Zaid-maker**
@AnandChowdhary 

Manually build the action on my local and it builds without any error so i assume that the last build fails due to build correctly.

Also i have replace `GH_PAT` with `GITHUB_SECRET` as it contains the required permissions to workflows to work on forks.

Replace ncc package with vercel's ncc package

Please take a close look to the chances u can tell me if anything needs to be changed!

### CODE REVIEW

**Comment by Zaid-maker** [comment]
The build script still have issues

**Comment by Zaid-maker** [comment]
@AnandChowdhary merge this

**Comment by AnandChowdhary** [comment]
I'm not sure why you're using both GITHUB_SECRET and GITHUB_TOKEN. Can you please explain? Thanks!

**Comment by AnandChowdhary** [comment]
Closing this as 70fca5e fixed it. If you want to replace the personal access token, I suggest you use:

```
token: ${{ secrets.GH_PAT || github.token }}
```

This way, we can fallback to the default GitHub token if there's no overwritten personal access token.

**Comment by Zaid-maker** [comment]
> Closing this as [70fca5e](https://github.com/AnandChowdhary/bookshelf-action/commit/70fca5e2595447328dbd0ac3aa1a087c47d8bb9a) fixed it. If you want to replace the personal access token, I suggest you use:
> 
> ```
> token: ${{ secrets.GH_PAT || github.token }}
> ```
> 
> This way, we can fallback to the default GitHub token if there's no overwritten personal access token.

Oh i didn't thought that but u should close the pr as it also contains other fixes did u check the changes correctly?

**Comment by AnandChowdhary** [comment]
I already updated @zeic/ncc to @vercel/ncc and the Node version, so maybe it's best that we do the token changes in a separate PR? Thank you for your flexibility and your contribution, much appreciated!

**Pull request closed without merging**
